# Generated by Django 5.1 on 2024-08-15 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DPCApp', '0002_rename_create_at_domaindetail_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domaindetail',
            name='domainSuffix',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domainDetail', to='DPCApp.domainsuffix'),
        ),
    ]
