# Generated by Django 5.1 on 2024-08-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DPCApp', '0003_alter_domaindetail_domainsuffix'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchedName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searchedName', models.CharField(max_length=250)),
                ('searchFreq', models.IntegerField()),
            ],
        ),
    ]
