# Generated by Django 5.1 on 2024-08-19 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DPCApp', '0004_searchedname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchedname',
            options={'ordering': ['-searchFreq']},
        ),
    ]
