# Generated by Django 5.1 on 2024-08-19 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DPCApp', '0005_alter_searchedname_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchedname',
            options={'ordering': ['-searchFreq', '-totalSearchFreq']},
        ),
        migrations.AddField(
            model_name='searchedname',
            name='totalSearchFreq',
            field=models.IntegerField(default=1),
        ),
    ]
