# Generated by Django 5.1 on 2024-08-20 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DPCApp', '0007_alter_searchedname_searchfreq'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchedname',
            name='stayIndex',
            field=models.IntegerField(default=1),
        ),
    ]
